export type JournalPost = {
  slug: string;
  title: string;
  excerpt: string;
  tag: string;
  date: string;
  readTime: string;
  author: string;
  content: string[];
};

export const journalPosts: JournalPost[] = [
  {
    slug: "returning-to-the-root",
    title: "Returning to the root: an intro to bitter herbs",
    excerpt:
      "Why bitter botanicals like dandelion and ginger have been digestion's quiet allies for centuries.",
    tag: "Herbalism",
    date: "June 4, 2026",
    readTime: "14 min read",
    author: "Pamela Espinoza",
    content: [
      "Long before probiotics lined the shelves of every grocery store, our grandmothers reached for something simpler: a bitter root, steeped slow, sipped before a meal. Bitterness is a flavor we have largely engineered out of modern food, and with it we have lost one of the body's oldest cues for digestion.",
      "When the tongue tastes bitter, a quiet cascade begins. Saliva increases. The stomach prepares acid. The liver nudges bile into motion. Nothing dramatic — just the body remembering how to do what it has always known.",
      "In our Gut Tonic, we lean on three plants that have carried this tradition for generations: dandelion root for the liver, ginger for warmth and motility, and gentian for that unmistakable, mouth-puckering bitterness. Together they are less of a supplement and more of an invitation — a small ritual to slow down before you eat.",
      "If you are new to bitters, start with a few drops on the tongue ten minutes before a meal. Notice the way your stomach softens. Notice that you chew a little longer. That is the plant doing its quiet work.",
      "To understand why bitterness matters so much, we have to look back. For thousands of years, across nearly every culture on earth, bitter plants were woven into the fabric of daily eating. In Europe, aperitifs made with gentian and wormwood were sipped before dinner to stoke the fires of digestion. In Traditional Chinese Medicine, bitter herbs were classified as cooling and descending, used to clear heat and drain downward when the body felt congested or inflamed. In Ayurveda, the bitter taste — tikta — was considered one of the six essential tastes, believed to support the liver, purify the blood, and reduce excess heat and inflammation in the body.",
      "What is remarkable is that these traditions, separated by geography and language, arrived at remarkably similar conclusions: bitter plants support the body's ability to break down food, move waste, and keep the liver clear. It was not one genius herbalist who figured this out. It was thousands of years of observation, trial, and quiet listening to the body. Our ancestors did not have microscopes or double-blind studies, but they had something arguably more reliable: time.",
      "And then, somewhere in the last century, we stopped. We bred bitterness out of our vegetables — modern lettuce is a pale shadow of the wild bitter greens our ancestors foraged. We replaced pre-meal bitters with antacids. We stopped eating the rinds, the peels, the roots, the wild plants that carried this flavor. In the process, we disconnected from one of the most reliable signals the body has for preparing itself to receive nourishment.",
      "The science, when it finally caught up, confirmed what traditional healers already knew. Bitter receptors — called T2R receptors — are not confined to the tongue. They are found throughout the gastrointestinal tract, in the pancreas, in the liver, even in the respiratory system. When activated by bitter compounds, these receptors trigger a coordinated digestive response: increased salivary amylase to begin breaking down carbohydrates, enhanced gastric acid secretion to denature proteins and activate digestive enzymes, increased bile flow to emulsify fats, and stimulation of the vagus nerve to improve gut motility. This is not vague folk wisdom. This is a well-documented physiological reflex.",
      "Dandelion root, one of the pillars of our Gut Tonic, is a perfect example of a bitter plant that has been both celebrated and dismissed. To the casual observer, it is a weed — something to be eradicated from a pristine lawn. But beneath that sunny yellow flower lies a root that has been used for liver support and gentle detoxification for centuries. Dandelion is what's known as a cholagogue — it stimulates bile production and flow, helping the liver process fats and move toxins out through the digestive tract. It also has a gentle diuretic effect, supporting the kidneys in their work of filtration without depleting potassium the way synthetic diuretics can. The root, when dried and roasted, carries a deep, earthy bitterness that feels ancient on the tongue. It tastes like something your body recognizes even if your modern palate does not.",
      "Ginger, our second plant, brings a different kind of warmth. Where dandelion root moves and clears, ginger ignites and circulates. It has been used across Asia, Africa, and the Middle East for over two thousand years as a digestive aid, anti-nausea remedy, and circulatory stimulant. Gingerol, the active compound in fresh ginger, and shogaol, which forms when ginger is dried, both have well-documented effects on gastric motility — essentially keeping things moving through the digestive tract at a healthy pace. For people who feel bloated after meals, or who notice food sitting heavy in their stomach, ginger is often the first plant I recommend. It is not aggressive. It does not force the body. It simply reminds the digestive system of its own rhythm.",
      "Gentian is the third voice in our trio, and it is the one that announces itself most boldly. A few drops of gentian tincture on the tongue produces a bitterness so profound it almost seems to vibrate. This is not a flavor you sip casually — it demands attention. And that demand is precisely the point. Gentian is one of the most reliable bitter stimulants in the herbal pharmacopeia, used for centuries in European herbal medicine to revive sluggish digestion, stimulate appetite in those who have lost it through illness or stress, and support liver function. It is not a background player. It is the director, calling the entire digestive orchestra to attention.",
      "What I have come to believe, after years of working with these plants and watching how people respond to them, is that the ritual matters as much as the chemistry. Taking a bitter tincture before a meal is not like swallowing a pill in a hurry. You have to taste it. You have to pause. You have to let your body register the signal. In that pause, something shifts. The shoulders drop. The breath deepens. The meal that follows is eaten more slowly, more mindfully, more gratefully. The bitter herb becomes a doorway into presence.",
      "This is why I resist calling our Gut Tonic a supplement. Supplements are things you add to compensate for a deficiency. Bitters are something else entirely. They are a restoration of relationship — between your body and the food you eat, between your nervous system and your digestive system, between the ancient wisdom of these plants and the modern life that has forgotten them. They are a small, daily act of remembering.",
      "If you are new to bitters, I want to offer you a few practical suggestions. Start small — three to five drops on the tongue ten to fifteen minutes before a meal. You do not need much. The tongue is sensitive, and a little goes a long way. Do not dilute it in water at first; the direct contact with the tongue is part of what triggers the digestive reflex. If the bitterness feels overwhelming, breathe through it. The sensation peaks quickly and then softens into a kind of clarity.",
      "Pay attention to what you notice. Some people feel an immediate increase in saliva. Others feel a gentle warmth in the stomach. Some find themselves naturally eating more slowly, chewing more thoroughly, stopping when full rather than stuffed. These are not side effects. They are the intended effects, rediscovered. Keep a simple journal for the first two weeks — just a few notes after meals about how you feel. You may be surprised by the patterns that emerge.",
      "There are also contraindications to be aware of. Bitters stimulate digestive secretions, so they are generally not recommended for people with active ulcers, severe acid reflux, or acute gallbladder inflammation. If you are pregnant, it is wise to consult with a knowledgeable practitioner, as some bitter herbs can stimulate uterine contractions in high doses. And if you are taking medications that are metabolized by the liver, be aware that bitters can increase bile flow and potentially alter drug absorption. These are not reasons to fear bitters, but they are reasons to approach them with respect and, when needed, guidance.",
      "What I hope for everyone who tries our Gut Tonic is not just better digestion — though that often comes. What I hope for is a shift in relationship with food, with the body, with the simple act of nourishment. We live in a culture that treats eating as fueling, as an interruption to be managed, as calories to be counted. Bitters offer a different story. They invite us to slow down, to taste, to receive. They remind us that digestion is not just a mechanical process but a deeply sensory and even emotional one. And they connect us, however briefly, to the long lineage of humans who have known that the right plant, at the right moment, can change everything.",
    ],
  },
  {
    slug: "the-case-against-melatonin",
    title: "The case against melatonin (and what we use instead)",
    excerpt:
      "How traditional nervines like passionflower and skullcap support sleep without dependence.",
    tag: "Sleep",
    date: "May 18, 2026",
    readTime: "16 min read",
    author: "Pamela Espinoza",
    content: [
      "Melatonin is a hormone. That sentence alone should give us pause. We take it casually — a gummy before bed, another on a long flight — but we are dosing a signal the body produces in tiny, precisely-timed amounts.",
      "What most people actually need is not more melatonin. It is a calmer nervous system at the end of the day. That is where the old nervines come in: passionflower, skullcap, California poppy. Plants that do not knock you out, but instead help your shoulders drop, your jaw unclench, your mind stop rehearsing tomorrow.",
      "Our Sleep Drops are built around this idea. Passionflower for the looping thoughts. Skullcap for the tense body. A whisper of chamomile to round it all out. No hangover, no dependency, no overriding the body's own rhythm.",
      "Sleep is not a problem to solve with a stronger sedative. It is a conversation with the nervous system. These plants are simply better translators.",
      "Let me say more about why I am concerned about melatonin, because my opposition is not reflexive — it is rooted in both physiology and observation. Melatonin is produced by the pineal gland in response to darkness. Its release is exquisitely sensitive to light exposure, circadian timing, and the overall health of the endocrine system. In a healthy adult, the body produces roughly 0.3 milligrams of melatonin per night. The typical over-the-counter supplement contains 1 to 10 milligrams — often ten to thirty times the physiological dose. This is not a subtle nudge to the system. It is a pharmacological override.",
      "The problems with this override are multiple. First, there is the question of tolerance. When you flood the system with exogenous melatonin night after night, the body may begin to downregulate its own production. The pineal gland, sensing that sufficient melatonin is already present, produces less. Over time, this can create a kind of dependency — not addiction in the clinical sense, but a situation where natural sleep onset becomes harder without the supplement. I have spoken with dozens of people who started melatonin for a short period of stress or travel and found themselves unable to sleep without it months or even years later.",
      "Second, melatonin is not just a sleep hormone. It plays roles in immune regulation, reproductive function, and mood. High doses can suppress ovulation in women and reduce sperm quality in men. In children, whose endocrine systems are still developing, the effects of chronic melatonin use are largely unknown — and that uncertainty alone should counsel caution. We are running an uncontrolled experiment on millions of people, including children, with a hormone that affects far more than sleep timing.",
      "Third, melatonin supplements are notoriously inconsistent in their actual dosage. Independent testing has found that many products contain far more or far less melatonin than the label claims, and some have been found to contain serotonin, a neurotransmitter with its own set of risks when taken unsupervised. The supplement industry is not regulated with the rigor of pharmaceuticals, and melatonin is no exception.",
      "So what do we do instead? We return to the nervines — a class of herbs that have supported human sleep for millennia without overriding the body's own systems. Nervines are plants that act on the nervous system to reduce tension, ease anxiety, and promote rest. They are not sedatives in the pharmaceutical sense. They do not force the brain into unconsciousness. They instead create the conditions under which sleep can emerge naturally.",
      "Passionflower is the crown jewel of our Sleep Drops, and for good reason. This climbing vine, with its otherworldly purple and white flowers, has been used by Indigenous peoples of the Americas for centuries as a calming agent. European herbalists adopted it in the sixteenth century, and it has remained a staple of Western herbal medicine ever since. Modern research supports what traditional use suggested: passionflower increases levels of gamma-aminobutyric acid (GABA) in the brain, the primary inhibitory neurotransmitter that helps calm neuronal activity and reduce anxiety. But it does so gently, without the risk of dependency or the grogginess associated with stronger pharmaceutical sedatives.",
      "What I love most about passionflower is the quality of sleep it produces. It does not knock you out so much as dissolve the barrier between wakefulness and sleep. People who use it often report falling asleep without the familiar struggle, and waking feeling genuinely refreshed rather than drugged. The looping thoughts that keep so many of us awake at night — the rehearsal of conversations, the tallying of tomorrow's tasks, the vague free-floating worry — seem to lose their grip. Passionflower does not silence the mind by force. It softens the mind into silence.",
      "Skullcap is our second primary herb, and it serves a slightly different purpose. Where passionflower addresses the mental chatter, skullcap addresses the physical tension that so often accompanies it. The body stores stress in the shoulders, the jaw, the belly, the hands. Many of my clients tell me they are not even aware of how tense they are until they take something that finally allows them to relax. Skullcap is that something. It is a direct relaxant to the neuromuscular system, easing muscle tension and the nervous hyperactivity that drives it.",
      "American skullcap, Scutellaria lateriflora, has a long history of use for nervous exhaustion, anxiety, and tension-related sleep disturbances. It was particularly popular in the nineteenth century, when herbal medicine was the primary form of healthcare in rural America. Eclectic physicians — a now-extinct but once-flourishing school of American herbal medicine — used skullcap extensively for what they called 'nervous irritation,' a catch-all for the kinds of tension and restlessness that modern life produces in abundance. The plant fell out of favor as pharmaceuticals rose, but it never lost its efficacy. It simply waited for us to remember.",
      "California poppy is the third herb in our blend, and it brings a quality that is harder to describe but easy to feel: a kind of gentle surrender. Eschscholzia californica is not an opium poppy. It contains no opiates and is non-addictive. But it does share some of the same alkaloid families, and it produces a mild sedative effect that is especially useful for people who lie awake with a sense of urgency — the feeling that sleep is something that must be achieved, that the night is ticking away, that rest is a race against the clock. California poppy softens that urgency into acceptance.",
      "I also include a small amount of chamomile in our Sleep Drops, more as a harmonizer than a primary actor. Chamomile is one of the most widely used calming herbs in the world, familiar to nearly everyone as a bedtime tea. Its active constituents, particularly apigenin, bind to benzodiazepine receptors in the brain and produce a mild sedative effect. In our blend, chamomile serves as the gentle rounding edge — the herb that ties the others together and makes the formula feel complete.",
      "The combination of these four plants is, in my experience, more effective than any of them alone. Passionflower quiets the mind. Skullcap releases the body. California poppy deepens surrender. Chamomile smooths the edges. Together they address the multiple dimensions of sleeplessness that plague modern people: mental chatter, physical tension, emotional urgency, and the general overstimulation of a life lived in electric light and digital noise.",
      "If you are currently using melatonin and want to transition away from it, I recommend a gradual approach. Begin by reducing your melatonin dose slightly while introducing the Sleep Drops about thirty minutes before bed. Do not expect an immediate, dramatic difference — the plants work more subtly than a hormone override, and your body may need time to remember its own rhythms. After a week or two, reduce the melatonin further. Most people find they can discontinue melatonin entirely within three to four weeks, though individual timelines vary.",
      "There are also lifestyle practices that support this transition. Dim the lights in your home after sunset. Avoid screens for at least an hour before bed, or use blue light blocking glasses if you must work late. Keep your bedroom cool and dark. These are not trendy wellness tips — they are physiological necessities. The body is designed to sleep in darkness and coolness, and when we deny it those conditions, no herb can fully compensate.",
      "I want to be clear that I am not categorically opposed to melatonin in all circumstances. For jet lag, for shift workers adjusting to a new schedule, for specific circadian rhythm disorders, melatonin can be a useful short-term tool. The problem is not the molecule. The problem is the casual, chronic, high-dose use that has become normalized in our culture. We have turned a finely tuned hormonal signal into a nightly sleeping pill, and in doing so we have forgotten that sleep is not something to be induced by force. It is something to be invited by creating the right conditions — in the body, in the mind, and in the environment.",
      "Our Sleep Drops are my attempt to offer a different invitation. They do not override your biology. They speak to it, in the language of plants that have been part of human sleep for longer than written history. They ask your nervous system to soften rather than commanding it to shut down. And in that softening, sleep finds its own way back.",
    ],
  },
  {
    slug: "a-morning-ritual-in-three-drops",
    title: "A morning ritual in three drops",
    excerpt:
      "A simple, slow practice for grounding your nervous system before the day begins.",
    tag: "Rituals",
    date: "April 29, 2026",
    readTime: "12 min read",
    author: "Pamela Espinoza",
    content: [
      "Before the phone. Before the email. Before the first conversation of the day. Three drops, under the tongue, and one full breath.",
      "This is not a productivity hack. It is the opposite. It is a small, deliberate pause that tells your body: we are not running yet. We are here first.",
      "I use our Gut Tonic in the morning — the bitterness wakes the system gently and sets digestion up for the day. Some mornings I follow it with a cup of warm water and lemon. Some mornings I do not. The ritual is the point, not the prescription.",
      "If you are looking for somewhere to start, start here. Three drops. One breath. Then begin.",
      "I want to tell you how this ritual came to be, because it was not designed in a workshop or copied from a wellness influencer. It emerged from necessity. A few years ago, I found myself waking up already anxious — my heart racing before my feet touched the floor, my mind already constructing the day's problems before I had even opened my eyes. I was sleeping poorly, eating distractedly, and moving through my days with a kind of low-grade panic that had become so normalized I barely noticed it anymore. I thought this was just adulthood. I thought this was just what life felt like when you were building something.",
      "What broke the pattern was not a dramatic intervention. It was a small, consistent act that interrupted the autopilot. I had been studying herbal medicine for years, and I knew about the digestive benefits of bitters. But I had always thought of them as something you took before a big dinner, or when your stomach felt off. It had never occurred to me to take them in the morning, as a kind of waking-up ritual, until a mentor of mine — an elder herbalist in New Mexico — mentioned that she gave bitters to her grandchildren every morning before school. Not for digestion, she said, but for grounding. 'It wakes the whole system up,' she told me. 'Not just the stomach. The whole body remembers it's alive.'",
      "I started the next day. Three drops of a simple dandelion and gentian tincture, straight on the tongue, before I did anything else. The first morning, the bitterness shocked me awake more effectively than any cup of coffee ever had. But it was a different kind of awake. Not jittery. Not anxious. Just present. My body registered the sensation, responded to it, and in that response I found myself actually inhabiting my morning rather than already fleeing from it into the day's demands.",
      "What I noticed over the following weeks was subtle but unmistakable. I ate breakfast more slowly, actually tasting my food. I was less reactive to the first email of the day — that jolt of adrenaline that used to set the tone for everything that followed. My digestion improved not because the herbs were magical, but because I was finally eating in a state of presence rather than distraction. The ritual had created a boundary, however thin, between sleep and the waking world. And that boundary gave me something I had not realized I was missing: a sense of agency over how I entered my day.",
      "The science behind morning bitters is fascinating and, I think, validates what my body intuited. The bitter taste triggers the cephalic phase of digestion — the preparatory response that begins in the brain before food even reaches the stomach. Saliva production increases. Gastric acid begins to flow. The liver and gallbladder prepare to process fats. The pancreas readies its enzymes. This is not just about digestion in the narrow sense. It is about priming the entire metabolic system for the day ahead. When we skip this phase — when we roll out of bed, scroll our phones, and shove food down while answering emails — we are essentially asking our bodies to run before they have warmed up.",
      "But the physiological explanation, while satisfying, does not fully capture what the ritual does. There is also a psychological dimension that I have come to value even more. The act of taking something bitter, deliberately, first thing in the morning, is an act of choosing discomfort over comfort. It is a small declaration that you are willing to meet the day as it is, not as you wish it to be. The bitterness is not pleasant. It does not need to be. It is real. And in a world of endless sweetness and distraction, there is something profoundly grounding in choosing to taste what is real.",
      "I have experimented with many variations of this ritual over the years, and I want to share what I have learned. The form of the bitter matters less than the consistency. Tinctures are convenient and potent, but a small cup of strong bitter tea works beautifully too. Some mornings, when I have time, I will grate fresh ginger into warm water and sip it slowly, letting the heat and pungency wake my system. Other mornings, when time is short, three drops of our Gut Tonic on the tongue takes ten seconds and accomplishes the same thing. The specific plant is less important than the act itself.",
      "What I do recommend, regardless of which bitter you choose, is the breath that follows. After taking the bitter, close your eyes and take one slow, full breath — in through the nose for a count of four, out through the mouth for a count of six. This is not complicated breathwork. It is simply a moment of acknowledgment. You are here. The day has not started yet. You have a choice about how you meet it. That breath, paired with the bitter taste still lingering on the tongue, becomes a kind of anchor. On difficult days, I return to it again and again — the memory of that first grounded moment, carried forward.",
      "There are mornings when I skip the ritual. I am traveling, or I am sick, or I am simply moving too fast and forget. I do not beat myself up about it. Rituals are meant to support life, not become another source of guilt. But I notice the difference on the days I skip. I feel less grounded, more reactive, more likely to be swept along by the current of the day rather than moving through it with intention. The ritual is not magic. It is practice. And like all practice, it works best when it is regular but not rigid.",
      "If you are drawn to try this, I suggest starting with just three days. Do not commit to a lifetime of morning rituals — that is too much pressure and almost guarantees failure. Commit to three mornings. Set out your bitters the night before, so they are waiting for you. Do not look at your phone before you take them. Taste the bitterness fully. Take one breath. Then proceed. At the end of the three days, notice how you feel. Notice your relationship to the morning. Notice whether the day feels a little more yours.",
      "I have had clients tell me that this small ritual changed their relationship with mornings entirely. One woman, a mother of three who had spent years waking up in a state of emergency, told me that the three drops and one breath became her 'sanctuary moment' — the only time of day that was fully hers, before the needs of her family swept her up. A man in his sixties, newly retired and struggling with the lack of structure, found that the morning ritual gave him a sense of purpose and continuity that his work schedule had previously provided. A college student with anxiety told me that the bitterness grounded her more effectively than any meditation app she had tried.",
      "What unites these stories is not the specific herb or the exact timing. It is the act of beginning the day with intention rather than reaction. It is the willingness to pause before the pause is taken from you. It is the recognition that how we enter the morning sets a tone that echoes through everything that follows. Three drops is not much. One breath is not long. But together, they can be the difference between a day that happens to you and a day that you meet with your full self.",
    ],
  },
];

export function getJournalPost(slug: string) {
  return journalPosts.find((p) => p.slug === slug);
}
